### ISSUE TITLE
Dependencies from node_modules not available upon initial `sb prepare`

### ISSUE THREAD

**Issue by joe4dev** [perfkit/hello-retail#1]
`# before first start: run 'npm install' !` should probably be part of `sb prepare` to automate everything.
Maybe there is a way to install only selected dependencies (with version pins!) without all the unnecessary dev stuff.

```
sb prepare --local
INFO:root:prepare()
INFO:root:docker=docker run --rm -v aws-secrets:/root/.aws -v /Users/joe/Projects/Serverless/test-apps-yes/hello-retail:/apps/hello-retail --entrypoint='' amaysim/serverless:2.8.0 /bin/sh -c "cd /apps/hello-retail && ./deploy.sh us-east-1 prod uniwue simont"
INFO:run:
INFO:run:
INFO:run:> hello-retail@0.1.0 root:deploy:all /apps/hello-retail
INFO:run:> npm run stream:deploy && npm run writer:deploy && npm run catalog:deploy:all && npm run photos:deploy:all && npm run web:deploy:all
INFO:run:
INFO:run:
INFO:run:> hello-retail@0.1.0 stream:deploy /apps/hello-retail
INFO:run:> ./build/0.env.sh && ./build/2.sls.sh deploy "Deploying Retail Stream"                          ./retail-stream
INFO:run:
INFO:run:
INFO:run:deploy Deploying Retail Stream in ./retail-stream
INFO:run:./build/2.sls.sh: line 15: /apps/hello-retail/node_modules/.bin/sls: not found
INFO:run:npm ERR! code ELIFECYCLE
INFO:run:npm ERR! syscall spawn
INFO:run:npm ERR! file sh
INFO:run:npm ERR! errno ENOENT
INFO:run:npm ERR! hello-retail@0.1.0 stream:deploy: `./build/0.env.sh && ./build/2.sls.sh deploy "Deploying Retail Stream"                          ./retail-stream`
INFO:run:npm ERR! spawn ENOENT
INFO:run:npm ERR!
INFO:run:npm ERR! Failed at the hello-retail@0.1.0 stream:deploy script.
INFO:run:npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
INFO:run:npm WARN Local package.json exists, but node_modules missing, did you mean to install?
INFO:run:
INFO:run:npm ERR! A complete log of this run can be found in:
INFO:run:npm ERR!     /root/.npm/_logs/2021-03-18T14_57_44_764Z-debug.log
INFO:run:npm ERR! code ELIFECYCLE
INFO:run:npm ERR! errno 1
INFO:run:npm ERR! hello-retail@0.1.0 root:deploy:all: `npm run stream:deploy && npm run writer:deploy && npm run catalog:deploy:all && npm run photos:deploy:all && npm run web:deploy:all`
INFO:run:npm ERR! Exit status 1
INFO:run:npm ERR!
INFO:run:npm ERR! Failed at the hello-retail@0.1.0 root:deploy:all script.
INFO:run:npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
INFO:run:npm WARN Local package.json exists, but node_modules missing, did you mean to install?
INFO:run:
INFO:run:npm ERR! A complete log of this run can be found in:
INFO:run:npm ERR!     /root/.npm/_logs/2021-03-18T14_57_44_861Z-debug.log
```

**Comment by simontrapp** [comment]
I tried reducing the dependencies, but it didn't work out well, since they are needed to compile/package the web component, so I kept it as is. I created a pull request which automates the installation process of dependencies on first use of sb. It should now work fine without using anything but `sb prepare`.

**Comment by joe4dev** [comment]
Ah, I see. It's quite astonishing how long some apps have to build dependencies (also for Python) for deploying a few lines of code 😅

After fixing the permissions of some scripts (chmod +x), I repeatedly get the following error (both local and docker mode) for the products-photo service:

```
INFO:run:> hello-retail@0.1.0 photos:deploy:3 /apps/hello-retail
INFO:run:> ./build/0.env.sh && ./build/2.sls.sh deploy "Deploying Product Photos - 2.Receive"             ./product-photos/2.receive
INFO:run:
INFO:run:
INFO:run:deploy Deploying Product Photos - 2.Receive in ./product-photos/2.receive
INFO:run:Serverless: Load command interactiveCli
INFO:run:Serverless: Load command config
INFO:run:Serverless: Load command config:credentials
INFO:run:Serverless: Load command config:tabcompletion
INFO:run:Serverless: Load command config:tabcompletion:install
INFO:run:Serverless: Load command config:tabcompletion:uninstall
INFO:run:Serverless: Load command create
INFO:run:Serverless: Load command install
INFO:run:Serverless: Load command package
INFO:run:Serverless: Load command deploy
INFO:run:Serverless: Load command deploy:function
INFO:run:Serverless: Load command deploy:list
INFO:run:Serverless: Load command deploy:list:functions
INFO:run:Serverless: Load command invoke
INFO:run:Serverless: Load command invoke:local
INFO:run:Serverless: Load command info
INFO:run:Serverless: Load command logs
INFO:run:Serverless: Load command metrics
INFO:run:Serverless: Load command print
INFO:run:Serverless: Load command remove
INFO:run:Serverless: Load command rollback
INFO:run:Serverless: Load command rollback:function
INFO:run:Serverless: Load command slstats
INFO:run:Serverless: Load command plugin
INFO:run:Serverless: Load command plugin
INFO:run:Serverless: Load command plugin:install
INFO:run:Serverless: Load command plugin
INFO:run:Serverless: Load command plugin:uninstall
INFO:run:Serverless: Load command plugin
INFO:run:Serverless: Load command plugin:list
INFO:run:Serverless: Load command plugin
INFO:run:Serverless: Load command plugin:search
INFO:run:Serverless: Load command config
INFO:run:Serverless: Load command config:credentials
INFO:run:Serverless: Load command rollback
INFO:run:Serverless: Load command rollback:function
INFO:run:Serverless: Load command upgrade
INFO:run:Serverless: Load command uninstall
INFO:run:Serverless: Load command login
INFO:run:Serverless: Load command logout
INFO:run:Serverless: Load command generate-event
INFO:run:Serverless: Load command test
INFO:run:Serverless: Load command dashboard
INFO:run:Serverless: Load command output
INFO:run:Serverless: Load command output:get
INFO:run:Serverless: Load command output:list
INFO:run:Serverless: Load command param
INFO:run:Serverless: Load command param:get
INFO:run:Serverless: Load command param:list
INFO:run:Serverless: Load command studio
INFO:run:Serverless: Deprecation warning: Starting with next major version, default value of provider.lambdaHashingVersion will be equal to "20201221"
INFO:run:            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
INFO:run:Serverless: Deprecation warning: Starting with next major version, API Gateway naming will be changed from "{stage}-{service}" to "{service}-{stage}".
INFO:run:            Set "provider.apiGateway.shouldStartNameWithService" to "true" to adapt to the new behavior now.
INFO:run:            More Info: https://www.serverless.com/framework/docs/deprecations/#AWS_API_GATEWAY_NAME_STARTING_WITH_SERVICE
INFO:run:Serverless: Invoke deploy
INFO:run:Serverless: Invoke package
INFO:run:Serverless: Invoke aws:common:validate
INFO:run:Serverless: Invoke aws:common:cleanupTempDir
INFO:run:Serverless: Packaging service...
INFO:run:Serverless: Excluding development dependencies...
INFO:run:
INFO:run:  Serverless Error ---------------------------------------
INFO:run:
INFO:run:  ServerlessError: Cannot read file node_modules/rxjs/src/operators/filter.ts due to: EIO: i/o error, open '/apps/hello-retail/product-photos/2.receive/node_modules/rxjs/src/operators/filter.ts'
INFO:run:      at /apps/hello-retail/node_modules/serverless/lib/plugins/package/lib/zipService.js:123:15
INFO:run:      at tryCatcher (/apps/hello-retail/node_modules/bluebird/js/release/util.js:16:23)
INFO:run:      at Promise._settlePromiseFromHandler (/apps/hello-retail/node_modules/bluebird/js/release/promise.js:547:31)
INFO:run:      at Promise._settlePromise (/apps/hello-retail/node_modules/bluebird/js/release/promise.js:604:18)
INFO:run:      at Promise._settlePromise0 (/apps/hello-retail/node_modules/bluebird/js/release/promise.js:649:10)
INFO:run:      at Promise._settlePromises (/apps/hello-retail/node_modules/bluebird/js/release/promise.js:725:18)
INFO:run:      at _drainQueueStep (/apps/hello-retail/node_modules/bluebird/js/release/async.js:93:12)
INFO:run:      at _drainQueue (/apps/hello-retail/node_modules/bluebird/js/release/async.js:86:9)
INFO:run:      at Async._drainQueues (/apps/hello-retail/node_modules/bluebird/js/release/async.js:102:5)
INFO:run:      at Immediate.Async.drainQueues [as _onImmediate] (/apps/hello-retail/node_modules/bluebird/js/release/async.js:15:14)
INFO:run:      at processImmediate (internal/timers.js:461:21)
INFO:run:
INFO:run:  Get Support --------------------------------------------
INFO:run:     Docs:          docs.serverless.com
INFO:run:     Bugs:          github.com/serverless/serverless/issues
INFO:run:     Issues:        forum.serverless.com
INFO:run:
INFO:run:  Your Environment Information ---------------------------
INFO:run:     Operating System:          linux
INFO:run:     Node Version:              12.19.0
INFO:run:     Framework Version:         2.25.2 (local)
INFO:run:     Plugin Version:            4.5.1
INFO:run:     SDK Version:               n/a
INFO:run:     Components Version:        3.7.5
INFO:run:
INFO:run:npm ERR! code ELIFECYCLE
INFO:run:npm ERR! errno 1
INFO:run:npm ERR! hello-retail@0.1.0 photos:deploy:3: `./build/0.env.sh && ./build/2.sls.sh deploy "Deploying Product Photos - 2.Receive"             ./product-photos/2.receive`
```

Any idea?

The file does exist:

```
ls -la product-photos/2.receive/node_modules/rxjs/src/operators/filter.ts  
-rw-r--r--  1 joe  staff  46 Oct 26  1985 product-photos/2.receive/node_modules/rxjs/src/operators/filter.ts
```


The previous services deployed successfully.

**Comment by simontrapp** [comment]
This one is new to me :D I didnt have any of these problems or permission problems on WSL. I will hopefully get to investigate in the next few days

**Comment by SimonEismann** [comment]
Attempted to replicate this, and on Linux, this works fine :)

**Comment by joe4dev** [comment]
Original dependency issue fixed (hence closing this issue).

Note: The `EIO: i/o error` persists on macOS (also confirmed by Sacheen)
Maybe some concurrency issue in combination with Docker bindmounds given the Serverless Framework wants to the the file content and stats concurrently [here](https://github.com/serverless/serverless/blob/84bcc1e26a0ea84a7cc665670c187ba4bd7c07fc/lib/plugins/package/lib/zipService.js#L121-L122)
